import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Case = {id:string; creator:string; state:string; input:{name:string;tax_id:string;description:string}; proposal?:Record<string,string>; proposal_digest?:string; created_at:string};
type Event = {id:number;actor:string;kind:string;detail:unknown;created_at:string};
function App(){
 const [key,setKey]=useState('');const [draftKey,setDraftKey]=useState('');const [cases,setCases]=useState<Case[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function api(path:string,data?:unknown,token=key){const response=await fetch('/api'+path,{method:data?'POST':'GET',headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Request failed');return result;}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('/cases',undefined,draftKey);setCases(result.cases);setKey(draftKey);setDraftKey('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!key)return <main className="entry"><div className="mark">F<span>·</span></div><p className="eyebrow">FOUNDRY / SUPPLIER OPERATIONS</p><h1>Good partnerships<br/>begin with evidence.</h1><p className="lede">One shared case. Independent agents.<br/>A decision that stays yours.</p><form onSubmit={login}><label>Access key<input aria-label="Access key" type="password" value={draftKey} onChange={e=>setDraftKey(e.target.value)} autoComplete="off" required/></label><button disabled={busy}>{busy?'Opening…':'Open supplier desk'}</button>{error&&<p role="alert">{error}</p>}</form><small>Your key stays in this tab. Closing or reloading signs you out.</small></main>;
 return <div className="layout"><aside><a className="brand" href="/">F<span>·</span> <strong>FOUNDRY</strong></a><p className="eyebrow">OPERATIONS DESK</p><div className="nav-active">◈ &nbsp; Supplier cases <b>{cases.length}</b></div><div className="aside-note">Evidence first.<br/>Approval stays human.</div><button className="quiet" onClick={()=>{setKey('');setCases([])}}>Sign out</button></aside><main className="workspace"><header><p className="eyebrow">PARTNER NETWORK / ONBOARDING</p><span className="live">● Services connected</span></header><div className="title"><div><h1>Supplier cases</h1><p>Follow the evidence. Review the exact record. Make the call.</p></div></div>{error&&<p className="error" role="alert">{error}</p>}<section className="surface empty"><h2>Your supplier queue</h2><p>{cases.length?`${cases.length} cases are ready to inspect.`:'A clean start. Add a supplier to begin independent checks.'}</p></section></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
